spring.application.name=pidev
spring.datasource.url=jdbc:mysql://localhost:3306/tourisme?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8089
<<<<<<< HEAD
server.servlet.context-path=/pidev




=======
server.servlet.context-path=/tourisme
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lefriiw@gmail.com
spring.mail.password=cwfu bwfk breu mrxe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Désactiver Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
>>>>>>> d01bd4c (Initial commit)


